### ISSUE TITLE
Vorschlag für Thema

### ISSUE THREAD

**Issue by Bertlinger** [ob-algdatii-ss18/leistungsnachweis-team-not-found#1]
Den von Ihnen geäußerten Themenwunsch zur graphischen Darstellung von Bäumen und Listen würden wir gerne bearbeiten.
Titel: Graphische Darstellung von Binärbäumen und einfach verketteten Listen.
Nutzung des ganzen soll so erfolgen, dass einfach eine funktion aufgerufen werden kann, der das root element übergeben wird (egal ob liste oder baum).
Rückgabewert wird ein boolean sein, der nur über Erfolg/misserfolg informiert.
Die eigentliche Ausgabe soll als .html file auf dem pc gesichert und per brower angeschaut werden können.

**Comment by Bertlinger** [comment]
Da ich gerade gesehen habe, dass bereits jemand B-Bäume macht - was auch immer genau dahinter steckt, könnten die Themen zu nah beisammen liegen.
Team B-Baum besteht ebenfalls aus nur 2 Membern, eventuell kann man die Teams zusammenlegen falls aufgabestellung glech ist?
Ansonsten wäre die Alternative ein Maze-Solver, der für gegebene Labrinthe (2D-Array) einen weg von eingang zu ausgang findet, diesen Protokolliert und eventuell noch optimiert.

**Comment by obcode** [comment]
Ein B-Baum ist was anderes (https://de.wikipedia.org/wiki/B-Baum). Üb der die Bearbeitung des Themenwunsches würde ich mich freuen. So einen Baum o.ä. können Sie schön mit Javascript-Bibliotheken zeichnen. Da müssten Sie dann nur das JSON ausgeben. Vielleicht im Browser dann noch mit Auto-Refresh oder Sie nehmen statt dem Browser den Electron, der darf auch Dateien lesen und schreiben.
